### PR TITLE
Update meta.yaml to match v1.9.0 requirements

### PR DESCRIPTION
**Pull request by connorferster**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by connorferster** [comment]
@jan-janssen It seems I am not able to merge this myself. Can you give me write access to the repo at after merging this?

**Comment by connorferster** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
> @jan-janssen It seems I am not able to merge this myself. Can you give me write access to the repo at after merging this?

Did you accept the invitation to join the `conda-forge` organisation here on Github? https://github.com/orgs/conda-forge/invitation

**Comment by connorferster** [comment]
Ah! I have now. Thanks again.

**Pull request merged**
